#!/usr/bin/env python3
"""
Huakaʻi: apply a curation patch from curate.html.

USAGE
    cd "/Library/WebServer/Documents/ahupuaa"
    source .venv/bin/activate

    # Save the JSON from curate.html into patch.json, then:
    python3 apply_patch.py patch.json

    # Or pipe it in:
    pbpaste | python3 apply_patch.py -

WHAT IT DOES
    Reads a patch in this shape:
      {
        "version": 1,
        "deletes": ["Original Name 1", "Original Name 2", ...],
        "renames": [{"from": "Old Name", "to": "New Name"}, ...]
      }
    For each delete:
      - removes the entry from data/locations.js
      - deletes the local image file (if img is "images/...")
    For each rename:
      - updates the entry's name field in data/locations.js
    Then rewrites IMAGE_CREDITS.md.

    Prints a summary, never touches anything not in the patch.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent
sys.path.insert(0, str(ROOT))
from download_images import (
    parse_locations, write_locations_js, write_credits,
    LOCATIONS_FILE, CREDITS_FILE,
)

def load_patch(arg):
    if arg == "-":
        text = sys.stdin.read()
    else:
        text = Path(arg).read_text(encoding="utf-8")
    return json.loads(text)

def main(patch_arg):
    patch = load_patch(patch_arg)
    deletes  = set(patch.get("deletes", []))
    renames  = {r["from"]: r["to"] for r in patch.get("renames", [])}
    print(f"Patch: {len(deletes)} deletes, {len(renames)} renames\n")

    locations = parse_locations(LOCATIONS_FILE)
    before = len(locations)

    kept = []
    deleted_names    = []
    deleted_images   = []
    deleted_missing  = []
    rename_applied   = []
    rename_missing   = list(renames.keys())

    images_to_remove = []
    perm_errors = []
    for loc in locations:
        name = loc["name"]
        if name in deletes:
            deleted_names.append(name)
            img = loc.get("img", "")
            if img.startswith("images/"):
                p = ROOT / img
                if p.exists():
                    try:
                        p.unlink()
                        deleted_images.append(img)
                    except PermissionError:
                        perm_errors.append(img)
                        images_to_remove.append(img)
                else:
                    deleted_missing.append(img)
            continue
        if name in renames:
            new_name = renames[name]
            loc["name"] = new_name
            rename_applied.append((name, new_name))
            if name in rename_missing:
                rename_missing.remove(name)
        kept.append(loc)

    after = len(kept)
    write_locations_js(kept, LOCATIONS_FILE)
    write_credits(kept, CREDITS_FILE)

    print(f"Entries before:  {before}")
    print(f"Entries deleted: {len(deleted_names)}")
    print(f"Entries renamed: {len(rename_applied)}")
    print(f"Entries after:   {after}")
    print(f"\nImage files deleted: {len(deleted_images)}")
    if deleted_missing:
        print(f"Image files already gone (no-op): {len(deleted_missing)}")
    if perm_errors:
        print(f"Image files I couldn't delete (permission): {len(perm_errors)}")
        # Write a shell script the user can run to remove them
        rm_script = ROOT / "remove_orphan_images.sh"
        with rm_script.open("w") as f:
            f.write("#!/bin/sh\n")
            f.write("# Auto-generated by apply_patch.py\n")
            f.write("# Removes images orphaned by the latest curation patch.\n")
            f.write("set -e\n")
            for p in images_to_remove:
                f.write(f'rm -f "{p}"\n')
        rm_script.chmod(0o755)
        print(f"Wrote {rm_script.name} — run it to clean up orphan image files.")

    not_found = deletes - set(deleted_names)
    if not_found:
        print(f"\nWARNING: {len(not_found)} delete name(s) didn't match any entry:")
        for n in sorted(not_found)[:10]:
            print(f"  - {n}")
        if len(not_found) > 10:
            print(f"  (and {len(not_found) - 10} more)")
    if rename_missing:
        print(f"\nWARNING: {len(rename_missing)} rename source(s) didn't match any entry:")
        for n in rename_missing[:10]:
            print(f"  - {n}")

    print("\nDone. data/locations.js and IMAGE_CREDITS.md updated.")
    print("Next: git add data/locations.js IMAGE_CREDITS.md images/")
    print("      git commit -m 'Curate: prune low-quality entries'")
    print("      git push")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python3 apply_patch.py <patch.json|->")
        sys.exit(1)
    main(sys.argv[1])
